In [1]:
import numpy as np
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout, Flatten, Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

num_samples = 100 # data sample count
time_steps = 500  # Number of time steps in each sample
num_sensors = 1   # Number of sensors

# Define the full file paths for your files
data_files = [
    "/Users/rashmikadushan/Github/TENG/BLE_Client/Sensor_Data/dushan_l_new.txt",
    "/Users/rashmikadushan/Github/TENG/BLE_Client/Sensor_Data/dushan_r_new.txt"
]
# label_file = "Our_Data/label_data.txt"

In [2]:
# Initialize an empty list to store data for each channel
input_data = []
input_labels = []

# Load data from each text file and append it to channel_data
# for filename in data_files:
for data_file in data_files:
    with open(data_file, 'r') as file:
        lines = file.readlines()
        channel_values = [list(map(float, line.strip().split())) for line in lines]
        input_data.append(channel_values)

combined_array = np.concatenate([input_data[0], input_data[1]], axis=0)
combined_array = combined_array[np.newaxis, ...]

x = np.array(combined_array).transpose(1, 2, 0)


In [3]:

print(np.shape(combined_array))

(1, 100, 500)


In [7]:

# Load labels from the label file
# with open(label_file, 'r') as file:
#     lines = file.readlines()
#     input_labels = [int(value) for line in lines for value in line.strip().split()]


for i in range(len(data_files)):
    label = np.full(len(input_data[i]),i)
    input_labels.append(label)

y_labels = np.array(input_labels).flatten()

y = to_categorical(y_labels-1,num_classes=2)  # One-hot encode the numerical labels

In [8]:
print(x.shape)
print(y_labels.shape)

(60, 500, 1)
(60,)


In [12]:
# check the data in right shape
print(x.shape)
print(y_labels.shape)
# print(x)
# print(y)

(100, 200, 1)
[[[ 7.]
  [ 7.]
  [ 1.]
  ...
  [20.]
  [ 5.]
  [ 4.]]

 [[ 0.]
  [ 7.]
  [ 0.]
  ...
  [ 7.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 7.]
  ...
  [ 5.]
  [ 7.]
  [ 9.]]

 ...

 [[ 0.]
  [ 0.]
  [ 0.]
  ...
  [69.]
  [81.]
  [86.]]

 [[ 0.]
  [ 0.]
  [16.]
  ...
  [12.]
  [ 9.]
  [ 9.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  ...
  [ 7.]
  [ 8.]
  [ 6.]]]


In [4]:
# Split the data into training and test sets
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
# Building the model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(time_steps, num_sensors)))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.5))

model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))  # 2 different people

# Compiling the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


In [10]:
# Training the model
model.fit(x, y, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 167ms/step - accuracy: 0.6042 - loss: 47.8497 - val_accuracy: 0.0000e+00 - val_loss: 75.1559
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5938 - loss: 103.9769 - val_accuracy: 0.6667 - val_loss: 6.2035
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5278 - loss: 79.9663 - val_accuracy: 0.0000e+00 - val_loss: 112.2992
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6528 - loss: 64.0428 - val_accuracy: 0.0000e+00 - val_loss: 104.1293
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6736 - loss: 61.3662 - val_accuracy: 0.0000e+00 - val_loss: 55.2594
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7465 - loss: 33.2495 - val_accuracy: 0.3333 - val_loss: 17.8405
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6528 - loss: 14.7726 - val_accuracy: 0.5833 - val_loss: 2.8109
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6215 - loss: 17.3611 -

In [11]:
model.save('trained_model_our.keras') # Save the trained model

In [1]:
from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.utils import to_categorical

model = load_model('trained_model_our.keras') # Load the trained model

In [67]:
array = np.random.randint(low=0, high=100, size=500)
array = array[np.newaxis, ..., np.newaxis]
print(np.shape(array))
pre = model.predict(array)
print(pre)
prediction = np.argmax(pre, axis=1)
print(prediction)

(1, 500, 1)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.97658175 0.02341824]]
[0]


In [6]:
# Define the full file paths for your files
test_data_files = [
    'sensor1_test.txt',
    'sensor2_test.txt',
    'sensor3_test.txt',
    'sensor4_test.txt',
    'sensor5_test.txt',
    'sensor6_test.txt'
]

test_label_file = "label_test.txt"

# Initialize an empty list to store data for each channel
input_test_data = []
input_test_labels = []

# Load data from each text file and append it to channel_data
# for filename in test_data_files:
with open('sensor1_test.txt', 'r') as file:
    lines = file.readlines()
    channel_values = [list(map(float, line.strip().split())) for line in lines]
    input_test_data.append(channel_values)

input_test_data = np.array(input_test_data)
x_test = input_test_data[:, 0:1, :]
x_test = np.array(x_test)
x_test = np.array(x_test).transpose(1, 2, 0)
print(np.shape(x_test))

# Load labels from the label file
with open(test_label_file, 'r') as file:
    lines = file.readlines()
    input_test_labels = [int(value) for line in lines for value in line.strip().split()]

y_test_labels = np.array(input_test_labels)

y_test = to_categorical(y_test_labels-1,num_classes=2)  # One-hot encode the numerical labels

# print(x_test)
# print(y_test)

(1, 200, 1)


In [7]:
print(x_test.shape)

# x_test = x_test[np.newaxis, ...]

(1, 200, 1)


In [8]:
# loss, accuracy = model.evaluate(x_test, y_test)
y_pred = model.predict(x_test)
y_pred_binary = np.argmax(y_pred, axis=1)
y_true_binary = np.argmax(y_test, axis=1)
print(y_true_binary)
print(y_pred_binary)

print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 1
'y' sizes: 26
